CREATE TABLE IF NOT EXISTS nodes (
    id INTEGER PRIMARY KEY,
    node_id VARCHAR(255) NOT NULL UNIQUE,
    ip VARCHAR(255) NOT NULL,
    port TINYINT NOT NULL,
    cpus TINYINT NOT NULL,
    cpu_arch INTEGER NOT NULL
);
