// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: capacity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMachineInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineInfoRequest) Reset() {
	*x = GetMachineInfoRequest{}
	mi := &file_capacity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineInfoRequest) ProtoMessage() {}

func (x *GetMachineInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capacity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMachineInfoRequest) Descriptor() ([]byte, []int) {
	return file_capacity_proto_rawDescGZIP(), []int{0}
}

type GetMachineInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int32                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram           int32                  `protobuf:"varint,2,opt,name=ram,proto3" json:"ram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineInfoResponse) Reset() {
	*x = GetMachineInfoResponse{}
	mi := &file_capacity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineInfoResponse) ProtoMessage() {}

func (x *GetMachineInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capacity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMachineInfoResponse) Descriptor() ([]byte, []int) {
	return file_capacity_proto_rawDescGZIP(), []int{1}
}

func (x *GetMachineInfoResponse) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *GetMachineInfoResponse) GetRam() int32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

var File_capacity_proto protoreflect.FileDescriptor

var file_capacity_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x61,
	0x6d, 0x32, 0x68, 0x0a, 0x0f, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x2e, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_capacity_proto_rawDescOnce sync.Once
	file_capacity_proto_rawDescData = file_capacity_proto_rawDesc
)

func file_capacity_proto_rawDescGZIP() []byte {
	file_capacity_proto_rawDescOnce.Do(func() {
		file_capacity_proto_rawDescData = protoimpl.X.CompressGZIP(file_capacity_proto_rawDescData)
	})
	return file_capacity_proto_rawDescData
}

var file_capacity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_capacity_proto_goTypes = []any{
	(*GetMachineInfoRequest)(nil),  // 0: capacity.GetMachineInfoRequest
	(*GetMachineInfoResponse)(nil), // 1: capacity.GetMachineInfoResponse
}
var file_capacity_proto_depIdxs = []int32{
	0, // 0: capacity.CapacityService.GetMachineInfo:input_type -> capacity.GetMachineInfoRequest
	1, // 1: capacity.CapacityService.GetMachineInfo:output_type -> capacity.GetMachineInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_capacity_proto_init() }
func file_capacity_proto_init() {
	if File_capacity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_capacity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capacity_proto_goTypes,
		DependencyIndexes: file_capacity_proto_depIdxs,
		MessageInfos:      file_capacity_proto_msgTypes,
	}.Build()
	File_capacity_proto = out.File
	file_capacity_proto_rawDesc = nil
	file_capacity_proto_goTypes = nil
	file_capacity_proto_depIdxs = nil
}
