// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: capacity.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapacityService_GetMachineInfo_FullMethodName = "/capacity.CapacityService/GetMachineInfo"
)

// CapacityServiceClient is the client API for CapacityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CapacityServiceClient interface {
	GetMachineInfo(ctx context.Context, in *GetMachineInfoRequest, opts ...grpc.CallOption) (*GetMachineInfoResponse, error)
}

type capacityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityServiceClient(cc grpc.ClientConnInterface) CapacityServiceClient {
	return &capacityServiceClient{cc}
}

func (c *capacityServiceClient) GetMachineInfo(ctx context.Context, in *GetMachineInfoRequest, opts ...grpc.CallOption) (*GetMachineInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMachineInfoResponse)
	err := c.cc.Invoke(ctx, CapacityService_GetMachineInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityServiceServer is the server API for CapacityService service.
// All implementations must embed UnimplementedCapacityServiceServer
// for forward compatibility.
type CapacityServiceServer interface {
	GetMachineInfo(context.Context, *GetMachineInfoRequest) (*GetMachineInfoResponse, error)
	mustEmbedUnimplementedCapacityServiceServer()
}

// UnimplementedCapacityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapacityServiceServer struct{}

func (UnimplementedCapacityServiceServer) GetMachineInfo(context.Context, *GetMachineInfoRequest) (*GetMachineInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachineInfo not implemented")
}
func (UnimplementedCapacityServiceServer) mustEmbedUnimplementedCapacityServiceServer() {}
func (UnimplementedCapacityServiceServer) testEmbeddedByValue()                         {}

// UnsafeCapacityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityServiceServer will
// result in compilation errors.
type UnsafeCapacityServiceServer interface {
	mustEmbedUnimplementedCapacityServiceServer()
}

func RegisterCapacityServiceServer(s grpc.ServiceRegistrar, srv CapacityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCapacityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapacityService_ServiceDesc, srv)
}

func _CapacityService_GetMachineInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityServiceServer).GetMachineInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityService_GetMachineInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityServiceServer).GetMachineInfo(ctx, req.(*GetMachineInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapacityService_ServiceDesc is the grpc.ServiceDesc for CapacityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapacityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capacity.CapacityService",
	HandlerType: (*CapacityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMachineInfo",
			Handler:    _CapacityService_GetMachineInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capacity.proto",
}
