// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: node_controller.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeController_RegisterNode_FullMethodName = "/novacloud.NodeController/RegisterNode"
)

// NodeControllerClient is the client API for NodeController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControllerClient interface {
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*Nothing, error)
}

type nodeControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControllerClient(cc grpc.ClientConnInterface) NodeControllerClient {
	return &nodeControllerClient{cc}
}

func (c *nodeControllerClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*Nothing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nothing)
	err := c.cc.Invoke(ctx, NodeController_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeControllerServer is the server API for NodeController service.
// All implementations must embed UnimplementedNodeControllerServer
// for forward compatibility.
type NodeControllerServer interface {
	RegisterNode(context.Context, *RegisterNodeRequest) (*Nothing, error)
	mustEmbedUnimplementedNodeControllerServer()
}

// UnimplementedNodeControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControllerServer struct{}

func (UnimplementedNodeControllerServer) RegisterNode(context.Context, *RegisterNodeRequest) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeControllerServer) mustEmbedUnimplementedNodeControllerServer() {}
func (UnimplementedNodeControllerServer) testEmbeddedByValue()                        {}

// UnsafeNodeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControllerServer will
// result in compilation errors.
type UnsafeNodeControllerServer interface {
	mustEmbedUnimplementedNodeControllerServer()
}

func RegisterNodeControllerServer(s grpc.ServiceRegistrar, srv NodeControllerServer) {
	// If the following call pancis, it indicates UnimplementedNodeControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeController_ServiceDesc, srv)
}

func _NodeController_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControllerServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeController_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControllerServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeController_ServiceDesc is the grpc.ServiceDesc for NodeController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novacloud.NodeController",
	HandlerType: (*NodeControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeController_RegisterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_controller.proto",
}
